"""empty message

Revision ID: c1a8287fc4f8
Revises: d7b864ff73f1
Create Date: 2019-10-18 13:07:55.494636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a8287fc4f8'
down_revision = 'd7b864ff73f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Items', sa.Column('expire_date', sa.DateTime(), nullable=True))
    op.add_column('Items', sa.Column('produce_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Items', 'produce_date')
    op.drop_column('Items', 'expire_date')
    # ### end Alembic commands ###
